[rewrite_local]
^https?:\/\/.*\.pangle\.com\/.* url reject
^https?:\/\/.*\.snssdk\.com\/.*ad.* url reject
^https?:\/\/.*\.snssdk\.com\/.*drama.*ad.* url reject
^https?:\/\/.*\.snssdk\.com\/.*reward.* url reject

[mitm]
hostname = *.snssdk.com,*.pangle.com
